apiVersion: apps/v1 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: cloud-example-app-deployment
spec:
  selector:
    matchLabels:
      app: cloud-example-app
  replicas: 1
  template:
    metadata:
      labels:
        app: cloud-example-app
    spec:
      containers:
      - name: cloud-app
        env:
          - name: APP_DATABASE
            value: postgres
          - name: APP_DATABASE_USER
            valueFrom:
              secretKeyRef:
                name: db-credentials
                key: db-user
          - name: APP_DATABASE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-credentials
                key: db-password
          - name: APP_DATABASE_URL
            value: postgres:5432
        image: jsgette/cloud-example-app:0.2.0
        ports:
          - containerPort: 8080
            name: server
        imagePullPolicy: Always
        tty: true
        resources:
          requests:
            memory: 512Mi
            cpu: 400m
          limits:
            memory: 512Mi
            cpu: 400m
