apiVersion: v1
kind: Pod
metadata:
  name: cloud-example-app
  labels:
    app: cloud-example-app
spec:
  containers:
    - name: cloud-app
      env:
        - name: APP_DATABASE
          value: postgres
        - name: APP_DATABASE_URL
          value: dbaas903.hyperp-dbaas.cloud.ibm.com:30180
      image: jsgette/cloud-example-app:0.1.0
      ports:
        - containerPort: 8080
          name: server
      imagePullPolicy: Always
      tty: true
      resources:
        requests:
          memory: 1Gi
          cpu: 500m
        limits:
          memory: 1Gi
          cpu: 500m